//! Makes cargo notice when a test case is added or removed.
//!
//! The test functions are generated by `test_derive::generate_tests!`, which
//! reads `src/tests/` while the crate is being compiled. Cargo cannot see
//! through a proc macro, so on its own it has no reason to recompile this
//! crate when a new `.cpl` file appears — the file would silently never run.
//!
//! The generated code `include_bytes!`s every case it found, which makes cargo
//! track the *contents* of the files that already exist. What it cannot track
//! that way is a file that was not there at expansion time, so this script
//! watches the directory and exports a fingerprint of the set of test files.
//! Adding or removing a case changes the fingerprint, which changes this
//! crate's build environment and forces the macro to be expanded again.

use std::hash::{DefaultHasher, Hasher};
use std::path::{Path, PathBuf};

/// Every `.cpl` file under `dir`, as paths relative to it, sorted so the
/// fingerprint depends on the set of files and not on directory order.
fn collect_cases(dir: &Path) -> Vec<PathBuf> {
    let mut cases = Vec::new();
    let Ok(entries) = std::fs::read_dir(dir) else {
        return cases;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            cases.extend(collect_cases(&path));
        } else if path.extension().is_some_and(|e| e == "cpl") {
            cases.push(path);
        }
    }

    cases.sort();
    cases
}

fn main() {
    let tests_dir = Path::new("src/tests");
    println!("cargo::rerun-if-changed={}", tests_dir.display());

    let mut hasher = DefaultHasher::new();
    for case in collect_cases(tests_dir) {
        hasher.write(case.to_string_lossy().as_bytes());
        hasher.write_u8(0);
    }

    println!("cargo::rustc-env=CPLANG_TEST_CASES_FINGERPRINT={:016x}", hasher.finish());
}
